#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = false
    enable_statusline_mode = true
    enable_filetree_gitstatus = true 
    autocomplete_method = "coc"
    default_indent = 4

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"

[[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30

[[layers]]
    name = "format"
    format_on_save = false

# C++
[[layers]]
    name = "lang#c"
    format_on_save = false

[layer.clang_std]
    cpp = "c++20"
    enable_clang_syntax_highlight = true

[[layers]]
  name = "checkers"
  enable = true

[[layers]]
    name = "lang#cmake"
    enable_typeinfo = true
    format_on_save = false

[[layers]]
    name = "core#statusline"

[[custom_plugins]]
    repo = "wellle/targets.vim"
    merged = false

[[custom_plugins]]
    repo = "nvim-lua/plenary.nvim"
    merged = false
[[custom_plugins]]
    repo = "nvim-telescope/telescope.nvim"
    merged = false

# Nerdtree
[[custom_plugins]]
    repo = "scrooloose/nerdtree"
    merged = false
[[custom_plugins]]
    repo = "Xuyuanp/nerdtree-git-plugin"
    merged = false

[[custom_plugins]]
    repo = "mustache/vim-mustache-handlebars"
    merged = false

[[layers]]
    name = "incsearch"

[[layers]]
  name = "shell"
  default_position = "bottom"
  default_height = 30
